Rework Kanedama
MansaGroup/kanedama pull request #21
Opened 2021-06-21 12:59 UTC by IamBlueSlime

Highly WIP.

2021-06-21 19:13 UTC, tristanleclercq requested changes

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +with the following insights:
```suggestion
with a wireframe to follow or a screenshot of our current dashboard. As mentioned above, your interface should however display the information shown below:
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +a baseline to your design choices and implementations.
```suggestion
The 2 screenshots above are only here to show the information required and provide
a baseline to your design choices and implementations.
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +The 2 screenshots do **not** represent our current dashboard nor the layout
```suggestion
They do **not** by any mean represent our current dashboard nor the layout
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +The view should only be for **one** user.
```suggestion
The view should only be for **one** single user.
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +end-to-end tests are a big plus. From our experience Cypress.js works very well
```suggestion
We expect you to test your code: the minimum requirement is unit tests.
End-to-end tests are a big plus. From our experience Cypress.js works very well
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +For business information, you'll have use the French SIRENE public API,
```suggestion
For business information, you'll have to use the French SIRENE public API,
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +| **GET** | /accounts/:account*id/transactions?from=\_start_date*&to=_end_date_ | Fetch the specified _account_id_ transactions from the _start_date_ to the _end_date_. Date are ISO 8601 UTC, so for
```suggestion
| **GET** | /accounts/:account*id/transactions?from=\_start_date*&to=_end_date_ | Fetch the specified _account_id_ transactions from the _start_date_ to the _end_date_. Date are ISO 8601 UTC, so for example `2018-08-13T03:24:00` It can't return more than **365 days** of transactions. If there are no dates specified, the oldest transaction will be returned |
```

2021-06-21 19:13 UTC, tristanleclercq commented on backend/README.md
> +| **GET**  | /accounts/:account*id/transactions?from=\_start_date*&to=_end_date_ | Fetch the specified _account_id_ transactions from the _start_date_ to the _end_date_. Date are ISO 8601 UTC, so for
```suggestion
| **GET**  | /accounts/:account*id/transactions?from=\_start_date*&to=_end_date_ | Fetch the specified _account_id_ transactions from the _start_date_ to the _end_date_. Date are ISO 8601 UTC, so for example `2018-08-13T03:24:00` It can't return more than **365 days** of transactions. If there are no dates specified, the oldest transaction will be returned |
```

2021-06-21 19:13 UTC, tristanleclercq commented on frontend/README.md
> +Here is a list of _nice-to-have_ bonuses is you may:
```suggestion
Here is a list of _nice-to-have_ bonuses:
```

2021-06-21 19:13 UTC, tristanleclercq commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
`Contributor Covenant` or `Code of Conduct` ? Both seems a bit odd

2021-06-28 13:16 UTC, IamBlueSlime commented on backend/README.md
> +3. Check if the user have at least **3 years of transaction history** between
I don't know, I've just re-worded and re-organized some parts without changing the core part of the tests.

2021-06-28 14:19 UTC, tristanleclercq approved these changes
Just a forgotten typo but apart from that lgtm 👍

2021-06-28 14:19 UTC, tristanleclercq commented on README.md
> +financial support hey deserve. We strive to offer to this underserved
```suggestion
financial support they deserve. We strive to offer to this underserved
```

2021-06-28 14:33 UTC, merged